
export const Cagoen : any[] = 
[ {
    textoPregunta: "¿En qué provincia se encuentra Tomellosa?",
    opcion1: "Toledo",
    opcion2: "Guadalajara",
    opcion3: "Ciudad Real",
    opcion4: "Cuenca",
    correcta: 3,
  },
  {
    textoPregunta: "¿Quién ganó el Oscar a Mejor Actor en 2020?",
    opcion1: "Brad Pitt",
    opcion2: "Joaquin Phoenix",
    opcion3: "Leonardo DiCaprio",
    opcion4: "Adam Driver",
    correcta: 2,
  },
  {
    textoPregunta: "¿Qué famoso emperador fue asesinado en los idus de marzo?",
    opcion1: "Nerón",
    opcion2: "Julio César",
    opcion3: "Marco Aurelio",
    opcion4: "Calígula",
    correcta: 2,
  },
  {
    textoPregunta: "¿Quién pintó la Mona Lisa?",
    opcion1: "Miguel Ángel",
    opcion2: "Rafael",
    opcion3: "Leonardo da Vinci",
    opcion4: "Donatello",
    correcta: 3,
  },
  {
    textoPregunta: "¿Cuál es el elemento químico con símbolo 'O'?",
    opcion1: "Oro",
    opcion2: "Osmio",
    opcion3: "Oxígeno",
    opcion4: "Oganesón",
    correcta: 3,
  },
  {
    textoPregunta: "¿En qué deporte se utiliza una pelota más grande?",
    opcion1: "Tenis",
    opcion2: "Baloncesto",
    opcion3: "Fútbol",
    opcion4: "Voleibol",
    correcta: 2,
  },
  {
    textoPregunta: "¿Cuál es la capital de Canadá?",
    opcion1: "Toronto",
    opcion2: "Vancouver",
    opcion3: "Ottawa",
    opcion4: "Montreal",
    correcta: 3,
  },
  {
    textoPregunta: "¿Cuál es la película más taquillera de todos los tiempos?",
    opcion1: "Avatar",
    opcion2: "Vengadores: Endgame",
    opcion3: "Titanic",
    opcion4: "Star Wars: El despertar de la fuerza",
    correcta: 1,
  },
  {
    textoPregunta: "¿En qué año comenzó la Primera Guerra Mundial?",
    opcion1: "1912",
    opcion2: "1914",
    opcion3: "1916",
    opcion4: "1918",
    correcta: 2,
  },{
    textoPregunta: "¿En qué país se encuentra la Torre Eiffel?",
    opcion1: "Italia",
    opcion2: "España",
    opcion3: "Francia",
    opcion4: "Alemania",
    correcta: 3,
  },
  {
    textoPregunta: "¿Cuál es el planeta más grande del sistema solar?",
    opcion1: "Júpiter",
    opcion2: "Saturno",
    opcion3: "Urano",
    opcion4: "Neptuno",
    correcta: 1,
  },
  {
    textoPregunta: "¿Quién escribió 'Don Quijote de la Mancha'?",
    opcion1: "Miguel de Cervantes",
    opcion2: "Gabriel García Márquez",
    opcion3: "Pablo Neruda",
    opcion4: "Federico García Lorca",
    correcta: 1,
  },
  {
    textoPregunta: "¿Qué país ganó el Mundial de Fútbol en 2018?",
    opcion1: "Alemania",
    opcion2: "Brasil",
    opcion3: "Francia",
    opcion4: "Argentina",
    correcta: 3,
  },
  {
    textoPregunta: "¿Cuál es el océano más grande del mundo?",
    opcion1: "Atlántico",
    opcion2: "Índico",
    opcion3: "Pacífico",
    opcion4: "Ártico",
    correcta: 3,
  },
  {
    textoPregunta: "¿Quién pintó el techo de la Capilla Sixtina?",
    opcion1: "Leonardo da Vinci",
    opcion2: "Miguel Ángel",
    opcion3: "Rafael",
    opcion4: "Tiziano",
    correcta: 2,
  },
  {
    textoPregunta: "¿Cuál es la capital de Australia?",
    opcion1: "Sídney",
    opcion2: "Melbourne",
    opcion3: "Canberra",
    opcion4: "Perth",
    correcta: 3,
  },
  {
    textoPregunta: "¿Cuál es el metal más ligero?",
    opcion1: "Hierro",
    opcion2: "Aluminio",
    opcion3: "Litio",
    opcion4: "Magnesio",
    correcta: 3,
  },
  {
    textoPregunta: "¿Qué país tiene más población?",
    opcion1: "India",
    opcion2: "Estados Unidos",
    opcion3: "China",
    opcion4: "Indonesia",
    correcta: 3,
  },
  {
    textoPregunta: "¿Cuál es el río más largo del mundo?",
    opcion1: "Nilo",
    opcion2: "Amazonas",
    opcion3: "Yangtsé",
    opcion4: "Misisipi",
    correcta: 2,
  },
  {
    textoPregunta: "¿Quién es el fundador de Microsoft?",
    opcion1: "Steve Jobs",
    opcion2: "Elon Musk",
    opcion3: "Bill Gates",
    opcion4: "Jeff Bezos",
    correcta: 3,
  },
  {
    textoPregunta: "¿En qué año llegó el hombre a la Luna?",
    opcion1: "1965",
    opcion2: "1969",
    opcion3: "1972",
    opcion4: "1975",
    correcta: 2,
  },
  {
    textoPregunta: "¿Cuál es el animal terrestre más rápido?",
    opcion1: "León",
    opcion2: "Tigre",
    opcion3: "Guepardo",
    opcion4: "Cebra",
    correcta: 3,
  },
  {
    textoPregunta: "¿Qué elemento tiene el símbolo químico 'H'?",
    opcion1: "Hidrógeno",
    opcion2: "Helio",
    opcion3: "Hierro",
    opcion4: "Hafnio",
    correcta: 1,
  },
  {
    textoPregunta: "¿Cuál es la ciudad más poblada del mundo?",
    opcion1: "Tokio",
    opcion2: "Nueva York",
    opcion3: "Shanghái",
    opcion4: "Mumbai",
    correcta: 1,
  },
  {
    textoPregunta: "¿Qué instrumento musical tocaba Ludwig van Beethoven?",
    opcion1: "Violín",
    opcion2: "Piano",
    opcion3: "Guitarra",
    opcion4: "Flauta",
    correcta: 2,
  },
  {
    textoPregunta: "¿Cuál es el país más pequeño del mundo?",
    opcion1: "Mónaco",
    opcion2: "San Marino",
    opcion3: "Vaticano",
    opcion4: "Liechtenstein",
    correcta: 3,
  },
  {
    textoPregunta: "¿Qué órgano del cuerpo humano bombea sangre?",
    opcion1: "Pulmones",
    opcion2: "Hígado",
    opcion3: "Corazón",
    opcion4: "Cerebro",
    correcta: 3,
  },
  {
    textoPregunta: "¿Cuál es la lengua más hablada en el mundo?",
    opcion1: "Español",
    opcion2: "Chino mandarín",
    opcion3: "Inglés",
    opcion4: "Hindú",
    correcta: 2,
  },
  {
    textoPregunta: "¿Quién fue el primer presidente de los Estados Unidos?",
    opcion1: "Abraham Lincoln",
    opcion2: "Thomas Jefferson",
    opcion3: "George Washington",
    opcion4: "John Adams",
    correcta: 3,
  },
  {
    textoPregunta: "¿Cuál es la montaña más alta del mundo?",
    opcion1: "K2",
    opcion2: "Everest",
    opcion3: "Makalu",
    opcion4: "Annapurna",
    correcta: 2,
  },
  {
    textoPregunta: "¿Qué país tiene más islas?",
    opcion1: "Indonesia",
    opcion2: "Noruega",
    opcion3: "Filipinas",
    opcion4: "Suecia",
    correcta: 4,
  },
  {
    textoPregunta: "¿Qué animal es conocido como el rey de la selva?",
    opcion1: "Elefante",
    opcion2: "León",
    opcion3: "Tigre",
    opcion4: "Gorila",
    correcta: 2,
  },
  {
    textoPregunta: "¿Cuál es la capital de Japón?",
    opcion1: "Osaka",
    opcion2: "Tokio",
    opcion3: "Kioto",
    opcion4: "Hiroshima",
    correcta: 2,
  },
  {
    textoPregunta: "¿Quién es el autor de 'Cien años de soledad'?",
    opcion1: "Gabriel García Márquez",
    opcion2: "Jorge Luis Borges",
    opcion3: "Mario Vargas Llosa",
    opcion4: "Pablo Neruda",
    correcta: 1,
  },
  {
    textoPregunta: "¿Qué gas necesitamos para respirar?",
    opcion1: "Oxígeno",
    opcion2: "Nitrógeno",
    opcion3: "Dióxido de carbono",
    opcion4: "Helio",
    correcta: 1,
  },
  {
    textoPregunta: "¿Qué continente tiene más países?",
    opcion1: "África",
    opcion2: "Asia",
    opcion3: "Europa",
    opcion4: "América",
    correcta: 1,
  },
  {
    textoPregunta: "¿Cuál es la forma más común de precipitación?",
    opcion1: "Nieve",
    opcion2: "Granizo",
    opcion3: "Lluvia",
    opcion4: "Rocío",
    correcta: 3,
  },
  {
    textoPregunta: "¿Cuál es el único continente sin desiertos?",
    opcion1: "Europa",
    opcion2: "Asia",
    opcion3: "América del Norte",
    opcion4: "Antártida",
    correcta: 1,
  },
  {
    textoPregunta: "¿Quién inventó la bombilla?",
    opcion1: "Albert Einstein",
    opcion2: "Alexander Graham Bell",
    opcion3: "Thomas Edison",
    opcion4: "Nikola Tesla",
    correcta: 3,
  },
  {
    textoPregunta: "¿Cuál es el color de la sangre cuando está dentro del cuerpo?",
    opcion1: "Rojo",
    opcion2: "Azul",
    opcion3: "Verde",
    opcion4: "Incolora",
    correcta: 2,
  },
  {
    textoPregunta: "¿Qué tipo de animal es la ballena?",
    opcion1: "Pez",
    opcion2: "Mamífero",
    opcion3: "Reptil",
    opcion4: "Anfibio",
    correcta: 2,
  },
  {
    textoPregunta: "¿Qué país tiene la mayor cantidad de volcanes activos?",
    opcion1: "Islandia",
    opcion2: "Estados Unidos",
    opcion3: "Japón",
    opcion4: "Indonesia",
    correcta: 4,
  },
  {
    textoPregunta: "¿Qué órgano del cuerpo humano filtra la sangre?",
    opcion1: "Riñón",
    opcion2: "Corazón",
    opcion3: "Pulmones",
    opcion4: "Hígado",
    correcta: 1,
  },
  {
    textoPregunta: "¿Qué moneda se utiliza en el Reino Unido?",
    opcion1: "Euro",
    opcion2: "Dólar",
    opcion3: "Libra esterlina",
    opcion4: "Franco",
    correcta: 3,
  },
  {
    textoPregunta: "¿Qué animal es el símbolo nacional de Canadá?",
    opcion1: "Alce",
    opcion2: "Castor",
    opcion3: "Oso",
    opcion4: "Bisonte",
    correcta: 2,
  },
  {
    textoPregunta: "¿Cuál es el metal más caro del mundo?",
    opcion1: "Oro",
    opcion2: "Platino",
    opcion3: "Rodio",
    opcion4: "Paladio",
    correcta: 3,
  },
  {
    textoPregunta: "¿Qué deporte se juega en Wimbledon?",
    opcion1: "Críquet",
    opcion2: "Fútbol",
    opcion3: "Tenis",
    opcion4: "Baloncesto",
    correcta: 3,
  },
  {
    textoPregunta: "¿Qué órgano es responsable de la digestión principal de los alimentos?",
    opcion1: "Hígado",
    opcion2: "Estómago",
    opcion3: "Intestinos",
    opcion4: "Páncreas",
    correcta: 2,
  },
  {
    textoPregunta: "¿Qué país es famoso por las pirámides de Giza?",
    opcion1: "México",
    opcion2: "Perú",
    opcion3: "Egipto",
    opcion4: "Sudán",
    correcta: 3,
  },
  {
    textoPregunta: "¿Qué país está entre México y Canadá?",
    opcion1: "Brasil",
    opcion2: "Estados Unidos",
    opcion3: "Cuba",
    opcion4: "Honduras",
    correcta: 2,
  },
  {
    textoPregunta: "¿Qué animal es conocido por su capacidad de cambiar de color?",
    opcion1: "Serpiente",
    opcion2: "Camaleón",
    opcion3: "Pulpo",
    opcion4: "Lagarto",
    correcta: 2,
  },
  {
    textoPregunta: "¿Qué país es el hogar de la famosa ópera de Sídney?",
    opcion1: "Reino Unido",
    opcion2: "Australia",
    opcion3: "Nueva Zelanda",
    opcion4: "Sudáfrica",
    correcta: 2,
  },
  {
    textoPregunta: "¿Cuál es el planeta más cercano al sol?",
    opcion1: "Venus",
    opcion2: "Tierra",
    opcion3: "Marte",
    opcion4: "Mercurio",
    correcta: 4,
  },
  {
    textoPregunta: "¿Cuál es el animal volador más rápido?",
    opcion1: "Halcón peregrino",
    opcion2: "Águila",
    opcion3: "Murciélago",
    opcion4: "Golondrina",
    correcta: 1,
  },
  {
    textoPregunta: "¿Qué gas es el más abundante en la atmósfera de la Tierra?",
    opcion1: "Oxígeno",
    opcion2: "Nitrógeno",
    opcion3: "Dióxido de carbono",
    opcion4: "Helio",
    correcta: 2,
  },
  {
    textoPregunta: "¿Qué país tiene el sistema ferroviario más extenso?",
    opcion1: "China",
    opcion2: "Rusia",
    opcion3: "Estados Unidos",
    opcion4: "India",
    correcta: 3,
  },
  {
    textoPregunta: "¿Qué país inventó el papel?",
    opcion1: "India",
    opcion2: "Egipto",
    opcion3: "China",
    opcion4: "Grecia",
    correcta: 3,
  },
  {
    textoPregunta: "¿Cuál es la capital de Grecia?",
    opcion1: "Atenas",
    opcion2: "Salónica",
    opcion3: "Corinto",
    opcion4: "Esparta",
    correcta: 1,
  },
  {
    textoPregunta: "¿Qué lengua tiene más palabras en su vocabulario?",
    opcion1: "Francés",
    opcion2: "Inglés",
    opcion3: "Ruso",
    opcion4: "Chino mandarín",
    correcta: 2,
  },
  {
    textoPregunta: "¿Cuál es el océano más frío del mundo?",
    opcion1: "Atlántico",
    opcion2: "Ártico",
    opcion3: "Índico",
    opcion4: "Pacífico",
    correcta: 2,
  },
  {
    textoPregunta: "¿Qué mineral es necesario para la formación de huesos y dientes?",
    opcion1: "Sodio",
    opcion2: "Potasio",
    opcion3: "Calcio",
    opcion4: "Hierro",
    correcta: 3,
  },
  {
    textoPregunta: "¿Quién pintó 'La Última Cena'?",
    opcion1: "Leonardo da Vinci",
    opcion2: "Pablo Picasso",
    opcion3: "Vincent van Gogh",
    opcion4: "Salvador Dalí",
    correcta: 1,
  },
  {
    textoPregunta: "¿Qué país tiene la mayor extensión territorial?",
    opcion1: "Estados Unidos",
    opcion2: "Brasil",
    opcion3: "Canadá",
    opcion4: "Rusia",
    correcta: 4,
  },
  {
    textoPregunta: "¿Qué famosa novela comienza con 'Llámame Ismael'?",
    opcion1: "Moby Dick",
    opcion2: "Don Quijote",
    opcion3: "Orgullo y prejuicio",
    opcion4: "Cumbres borrascosas",
    correcta: 1,
  },
  {
    textoPregunta: "¿Cuál es el metal más común en la corteza terrestre?",
    opcion1: "Hierro",
    opcion2: "Aluminio",
    opcion3: "Cobre",
    opcion4: "Oro",
    correcta: 2,
  },
  {
    textoPregunta: "¿Cuál es la capital de Argentina?",
    opcion1: "Córdoba",
    opcion2: "Buenos Aires",
    opcion3: "Rosario",
    opcion4: "Mendoza",
    correcta: 2,
  },
  {
    textoPregunta: "¿Qué sustancia en las plantas hace posible la fotosíntesis?",
    opcion1: "Clorofila",
    opcion2: "Glucosa",
    opcion3: "Agua",
    opcion4: "Oxígeno",
    correcta: 1,
  },
  {
    textoPregunta: "¿En qué continente se encuentra el desierto del Sahara?",
    opcion1: "Asia",
    opcion2: "África",
    opcion3: "Oceanía",
    opcion4: "América",
    correcta: 2,
  },
  {
    textoPregunta: "¿Qué animal es conocido por su gran memoria?",
    opcion1: "Delfín",
    opcion2: "Elefante",
    opcion3: "Perro",
    opcion4: "Caballo",
    correcta: 2,
  },
  {
    textoPregunta: "¿Qué tipo de estrella es el Sol?",
    opcion1: "Supergigante",
    opcion2: "Enana blanca",
    opcion3: "Gigante roja",
    opcion4: "Enana amarilla",
    correcta: 4,
  },
  {
    textoPregunta: "¿En qué país se encuentran las ruinas de Machu Picchu?",
    opcion1: "Chile",
    opcion2: "Colombia",
    opcion3: "Perú",
    opcion4: "Bolivia",
    correcta: 3,
  },
  {
    textoPregunta: "¿Qué océano está entre América y Europa?",
    opcion1: "Pacífico",
    opcion2: "Atlántico",
    opcion3: "Índico",
    opcion4: "Ártico",
    correcta: 2,
  },
  {
    textoPregunta: "¿Qué vitamina es producida por la piel cuando se expone al sol?",
    opcion1: "Vitamina C",
    opcion2: "Vitamina D",
    opcion3: "Vitamina B12",
    opcion4: "Vitamina A",
    correcta: 2,
  },
  {
    textoPregunta: "¿Qué país es conocido por el Monte Kilimanjaro?",
    opcion1: "Kenia",
    opcion2: "Tanzania",
    opcion3: "Uganda",
    opcion4: "Ruanda",
    correcta: 2,
  },
  {
    textoPregunta: "¿Quién fue el primer ser humano en el espacio?",
    opcion1: "Neil Armstrong",
    opcion2: "Yuri Gagarin",
    opcion3: "Buzz Aldrin",
    opcion4: "John Glenn",
    correcta: 2,
  },
  {
    textoPregunta: "¿En qué continente se encuentra Brasil?",
    opcion1: "América del Norte",
    opcion2: "África",
    opcion3: "América del Sur",
    opcion4: "Europa",
    correcta: 3,
  },
  {
    textoPregunta: "¿Qué famoso detective fue creado por Arthur Conan Doyle?",
    opcion1: "Hércules Poirot",
    opcion2: "Sherlock Holmes",
    opcion3: "Sam Spade",
    opcion4: "Philip Marlowe",
    correcta: 2,
  },
  {
    textoPregunta: "¿Qué animal es conocido por su velocidad en el agua?",
    opcion1: "Delfín",
    opcion2: "Tiburón",
    opcion3: "Orca",
    opcion4: "Atún",
    correcta: 1,
  },
  {
    textoPregunta: "¿Cuál es el idioma oficial de Brasil?",
    opcion1: "Portugués",
    opcion2: "Español",
    opcion3: "Francés",
    opcion4: "Inglés",
    correcta: 1,
  },
  {
    textoPregunta: "¿Qué planeta tiene anillos visibles?",
    opcion1: "Marte",
    opcion2: "Júpiter",
    opcion3: "Saturno",
    opcion4: "Neptuno",
    correcta: 3,
  },
  {
    textoPregunta: "¿En qué país se encuentra la Estatua de la Libertad?",
    opcion1: "Canadá",
    opcion2: "Estados Unidos",
    opcion3: "Francia",
    opcion4: "México",
    correcta: 2,
  },
  {
    textoPregunta: "¿Qué mamífero es conocido por volar?",
    opcion1: "Murciélago",
    opcion2: "Ardilla voladora",
    opcion3: "Colibrí",
    opcion4: "Pingüino",
    correcta: 1,
  },
  {
    textoPregunta: "¿Cuál es la moneda oficial de Japón?",
    opcion1: "Won",
    opcion2: "Dólar",
    opcion3: "Yen",
    opcion4: "Rupia",
    correcta: 3,
  },
  {
    textoPregunta: "¿Qué país es famoso por sus tulipanes?",
    opcion1: "Dinamarca",
    opcion2: "Holanda",
    opcion3: "Bélgica",
    opcion4: "Suecia",
    correcta: 2,
  },
];
            